#!/usr/bin/env python3
"""Deterministic 30-session synthetic corpus for the "many bars" case of the hoops Progress chart.

  python3 tests/generate-synthetic-sessions.py          # rewrite tests/fixtures/synthetic-30-sessions.json

Shape is the same as hoops-rows-2026-09-18.json (a snapshot of hoops.sessions + hoops.shot_events), so
compute-expected-metrics.py --rows can turn it into ground truth, and a test can feed it to the pure
functions in apps/web/lib/dashboard-data.ts. 30 sessions on 30 distinct UTC days (2026-06-01 .. 2026-06-30,
one device), 8-40 shots each, seeded, no swish-heavy 1-shot sessions, so every eFG% <= 100 and the
"Jan 1 / 1970" and "150 %" anomalies of the real corpus do not appear here. Device id is a test label.
"""
import json, os, random, uuid
from datetime import datetime, timedelta, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "fixtures", "synthetic-30-sessions.json")


def main():
    rng = random.Random(20260918)
    sessions, events = [], []
    for day in range(30):
        start = datetime(2026, 6, 1, 17, 0, tzinfo=timezone.utc) + timedelta(days=day, minutes=rng.randint(0, 90))
        sid = str(uuid.UUID(int=rng.getrandbits(128), version=4))
        n = rng.randint(8, 40)
        fg = rng.uniform(0.35, 0.78)
        t = start
        for i in range(n):
            t = t + timedelta(seconds=rng.randint(8, 40), milliseconds=rng.randint(0, 999))
            made = rng.random() < fg
            events.append({
                "id": str(uuid.UUID(int=rng.getrandbits(128), version=4)),
                "session_id": sid,
                "captured_at": t.strftime("%Y-%m-%d %H:%M:%S.") + f"{t.microsecond // 1000:03d}+00",
                "result": "made" if made else "missed",
                "x": round(rng.uniform(0.05, 0.95), 6),
                "y": round(rng.uniform(0.05, 0.95), 6),
                "confidence": round(rng.uniform(0.55, 0.99), 6),
                "frame_id": None,
                "swish": bool(made and rng.random() < 0.25),
            })
        # keep the README's v1 eFG% proxy at or below 100 for every synthetic session
        mine = events[-n:]
        while sum(e["result"] == "made" for e in mine) + 0.5 * sum(e["swish"] for e in mine) > n:
            next(e for e in mine if e["swish"])["swish"] = False
        sessions.append({
            "id": sid, "device_id": "synthetic-30-day-device",
            "started_at": start.strftime("%Y-%m-%d %H:%M:%S.000+00"),
            "ended_at": t.strftime("%Y-%m-%d %H:%M:%S.000+00"),
            "title": f"Synthetic day {day + 1:02d}",
            "created_at": start.strftime("%Y-%m-%d %H:%M:%S.000+00"),
        })
    out = {
        "snapshot_of": "synthetic (not a database snapshot)",
        "taken_at": "generated by tests/generate-synthetic-sessions.py, seed 20260918",
        "note": "30 sessions on 30 UTC days in June 2026; for the Progress chart 'many bars' bar in the spec (story 3).",
        "sessions": sessions, "shot_events": events,
    }
    json.dump(out, open(OUT, "w"), indent=1)
    print(f"wrote {OUT}: {len(sessions)} sessions, {len(events)} shots")


if __name__ == "__main__":
    main()
